// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
class Vtop_itch_pkg;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:
    // CELLS
    Vtop_itch_pkg* __PVT__itch_pkg;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(s_tkeep,7,0);
        VL_IN8(s_tvalid,0,0);
        VL_IN8(s_tlast,0,0);
        VL_OUT8(m_bbo_valid,0,0);
        VL_OUT8(m_bid_valid,0,0);
        VL_OUT8(m_ask_valid,0,0);
        VL_OUT8(ready,0,0);
        CData/*0:0*/ feed_handler_top__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__rst;
        CData/*7:0*/ feed_handler_top__DOT__s_tkeep;
        CData/*0:0*/ feed_handler_top__DOT__s_tvalid;
        CData/*0:0*/ feed_handler_top__DOT__s_tlast;
        CData/*0:0*/ feed_handler_top__DOT__m_bbo_valid;
        CData/*0:0*/ feed_handler_top__DOT__m_bid_valid;
        CData/*0:0*/ feed_handler_top__DOT__m_ask_valid;
        CData/*0:0*/ feed_handler_top__DOT__ready;
        CData/*7:0*/ feed_handler_top__DOT__hp_tkeep;
        CData/*0:0*/ feed_handler_top__DOT__hp_tvalid;
        CData/*0:0*/ feed_handler_top__DOT__hp_tlast;
        CData/*7:0*/ feed_handler_top__DOT__mf_len;
        CData/*0:0*/ feed_handler_top__DOT__mf_valid;
        CData/*2:0*/ feed_handler_top__DOT__dc_op;
        CData/*0:0*/ feed_handler_top__DOT__dc_valid;
        CData/*0:0*/ feed_handler_top__DOT__dc_side;
        CData/*0:0*/ feed_handler_top__DOT__dc_tick_ok;
        CData/*0:0*/ feed_handler_top__DOT__ot_valid;
        CData/*0:0*/ feed_handler_top__DOT__ot_m_valid;
        CData/*0:0*/ feed_handler_top__DOT__ot_m_side;
        CData/*0:0*/ feed_handler_top__DOT__ot_m_add;
        CData/*0:0*/ feed_handler_top__DOT__ot_m_done;
        CData/*0:0*/ feed_handler_top__DOT__pl_bid_valid;
        CData/*0:0*/ feed_handler_top__DOT__pl_ask_valid;
        CData/*0:0*/ feed_handler_top__DOT__pl_bbo_valid;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__rst;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__s_valid;
        CData/*2:0*/ feed_handler_top__DOT__u_orders__DOT__s_op;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__s_side;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__s_tick_ok;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__m_valid;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__m_side;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__m_add;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__m_done;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__ready;
        CData/*1:0*/ feed_handler_top__DOT__u_orders__DOT__state;
        CData/*2:0*/ feed_handler_top__DOT__u_orders__DOT__op_kind;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__op_side;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__op_tick_ok;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__pend_v;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__pend_valid;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__pend_side;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__accept;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__is_add;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__is_red;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__is_del;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__is_rep;
        CData/*7:0*/ feed_handler_top__DOT__u_orders__DOT__a_we;
        CData/*7:0*/ feed_handler_top__DOT__u_orders__DOT__b_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__hit_a;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__free_a_ok;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__sh_a;
        CData/*2:0*/ feed_handler_top__DOT__u_orders__DOT__hit_way_a;
    };
    struct {
        CData/*2:0*/ feed_handler_top__DOT__u_orders__DOT__free_way_a;
        CData/*3:0*/ feed_handler_top__DOT__u_orders__DOT__sh_idx_a;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__found_a;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__e_ladder;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__e_side;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__same_set;
        CData/*7:0*/ feed_handler_top__DOT__u_orders__DOT__valid_b;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__hit_b;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__free_b_ok;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__sh_b;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__st_free_ok;
        CData/*2:0*/ feed_handler_top__DOT__u_orders__DOT__hit_way_b;
        CData/*2:0*/ feed_handler_top__DOT__u_orders__DOT__free_way_b;
        CData/*3:0*/ feed_handler_top__DOT__u_orders__DOT__sh_idx_b;
        CData/*3:0*/ feed_handler_top__DOT__u_orders__DOT__st_free_idx;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__add_to_set;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__add_to_st;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__add_ok;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__rep_to_set;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__rep_to_st;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__rep_ok;
        CData/*2:0*/ feed_handler_top__DOT__u_orders__DOT__add_way;
        CData/*2:0*/ feed_handler_top__DOT__u_orders__DOT__rep_way;
        CData/*3:0*/ feed_handler_top__DOT__u_orders__DOT__add_st;
        CData/*3:0*/ feed_handler_top__DOT__u_orders__DOT__rep_st;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__a_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__a_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__b_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__b_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__a_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__a_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__b_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__b_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__a_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__a_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__b_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__b_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__a_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__a_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__b_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__b_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__a_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__a_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__b_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__b_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__a_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__a_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__b_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__b_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__a_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__a_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__b_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__b_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__a_en;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__a_we;
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__b_en;
    };
    struct {
        CData/*0:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__b_we;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__rst;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__s_valid;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__s_side;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__s_add;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__s_done;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__m_bbo_valid;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__m_bid_valid;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__m_ask_valid;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__s1_valid;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__s1_side;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__s1_add;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__s1_done;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__s1_occupied;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__wr_valid;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__wr_side;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__wr_done;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__fwd_hit;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__underflow;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__have_bid;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__have_ask;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__bid_we;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__ask_we;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_bbo__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_bbo__DOT__we;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_bbo__DOT__re;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_bbo__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_bbo__DOT__we;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_bbo__DOT__re;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_upd__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_upd__DOT__we;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_upd__DOT__re;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_upd__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_upd__DOT__we;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_upd__DOT__re;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__any;
        CData/*5:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__grp;
        CData/*5:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__off;
        CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__any;
        CData/*5:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__grp;
        CData/*5:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__off;
        CData/*0:0*/ feed_handler_top__DOT__u_decode__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_decode__DOT__rst;
        CData/*7:0*/ feed_handler_top__DOT__u_decode__DOT__s_len;
        CData/*0:0*/ feed_handler_top__DOT__u_decode__DOT__s_valid;
        CData/*2:0*/ feed_handler_top__DOT__u_decode__DOT__m_op;
        CData/*0:0*/ feed_handler_top__DOT__u_decode__DOT__m_valid;
        CData/*0:0*/ feed_handler_top__DOT__u_decode__DOT__m_side;
        CData/*0:0*/ feed_handler_top__DOT__u_decode__DOT__m_tick_ok;
        CData/*7:0*/ feed_handler_top__DOT__u_decode__DOT__msg_type;
        CData/*0:0*/ feed_handler_top__DOT__u_decode__DOT__add_side;
        CData/*2:0*/ feed_handler_top__DOT__u_decode__DOT__op_c;
        CData/*0:0*/ feed_handler_top__DOT__u_decode__DOT__side_c;
        CData/*0:0*/ feed_handler_top__DOT__u_decode__DOT__has_price;
        CData/*0:0*/ feed_handler_top__DOT__u_decode__DOT__in_band;
        CData/*0:0*/ feed_handler_top__DOT__u_decode__DOT__subpenny_c;
        CData/*0:0*/ feed_handler_top__DOT__u_frame__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_frame__DOT__rst;
        CData/*7:0*/ feed_handler_top__DOT__u_frame__DOT__s_tkeep;
        CData/*0:0*/ feed_handler_top__DOT__u_frame__DOT__s_tvalid;
        CData/*0:0*/ feed_handler_top__DOT__u_frame__DOT__s_tlast;
        CData/*7:0*/ feed_handler_top__DOT__u_frame__DOT__m_len;
        CData/*0:0*/ feed_handler_top__DOT__u_frame__DOT__m_valid;
    };
    struct {
        CData/*7:0*/ feed_handler_top__DOT__u_frame__DOT__nvalid;
        CData/*0:0*/ feed_handler_top__DOT__u_frame__DOT__desync;
        CData/*3:0*/ feed_handler_top__DOT__u_frame__DOT__in_bytes;
        CData/*7:0*/ feed_handler_top__DOT__u_frame__DOT__nv_ins;
        CData/*7:0*/ feed_handler_top__DOT__u_frame__DOT__total_len;
        CData/*0:0*/ feed_handler_top__DOT__u_frame__DOT__have_len;
        CData/*0:0*/ feed_handler_top__DOT__u_frame__DOT__have_msg;
        CData/*0:0*/ feed_handler_top__DOT__u_frame__DOT__len_sane;
        CData/*0:0*/ feed_handler_top__DOT__u_frame__DOT__bad_len;
        CData/*7:0*/ feed_handler_top__DOT__u_frame__DOT__nv_next;
        CData/*0:0*/ feed_handler_top__DOT__u_frame__DOT__frame_err;
        CData/*0:0*/ feed_handler_top__DOT__u_hdr__DOT__clk;
        CData/*0:0*/ feed_handler_top__DOT__u_hdr__DOT__rst;
        CData/*7:0*/ feed_handler_top__DOT__u_hdr__DOT__s_tkeep;
        CData/*0:0*/ feed_handler_top__DOT__u_hdr__DOT__s_tvalid;
        CData/*0:0*/ feed_handler_top__DOT__u_hdr__DOT__s_tlast;
        CData/*7:0*/ feed_handler_top__DOT__u_hdr__DOT__m_tkeep;
        CData/*0:0*/ feed_handler_top__DOT__u_hdr__DOT__m_tvalid;
        CData/*0:0*/ feed_handler_top__DOT__u_hdr__DOT__m_tlast;
        CData/*7:0*/ feed_handler_top__DOT__u_hdr__DOT__beat_idx;
        CData/*0:0*/ feed_handler_top__DOT__u_hdr__DOT__vlan_tagged;
        CData/*0:0*/ feed_handler_top__DOT__u_hdr__DOT__is_ipv4;
        CData/*0:0*/ feed_handler_top__DOT__u_hdr__DOT__is_udp;
        CData/*7:0*/ feed_handler_top__DOT__u_hdr__DOT__ip_off;
        CData/*7:0*/ feed_handler_top__DOT__u_hdr__DOT__ihl_bytes;
        CData/*7:0*/ feed_handler_top__DOT__u_hdr__DOT__udp_off;
        CData/*7:0*/ feed_handler_top__DOT__u_hdr__DOT__mold_off;
        CData/*7:0*/ feed_handler_top__DOT__u_hdr__DOT__payload_off;
        CData/*2:0*/ feed_handler_top__DOT__u_hdr__DOT__r_off;
        CData/*7:0*/ feed_handler_top__DOT__u_hdr__DOT__emit_start;
        CData/*0:0*/ feed_handler_top__DOT__u_hdr__DOT__pkt_ok;
        CData/*0:0*/ feed_handler_top__DOT__u_hdr__DOT__flush_pend;
        CData/*6:0*/ feed_handler_top__DOT__u_hdr__DOT__sh_lo;
        CData/*6:0*/ feed_handler_top__DOT__u_hdr__DOT__sh_hi;
        CData/*2:0*/ feed_handler_top__DOT__u_hdr__DOT__last_bytes;
        CData/*3:0*/ feed_handler_top__DOT__u_hdr__DOT__keep_shift;
        CData/*7:0*/ feed_handler_top__DOT__u_hdr__DOT__last_keep;
        CData/*0:0*/ feed_handler_top__DOT__u_hdr__DOT__do_emit;
        CData/*0:0*/ __Vfunc_feed_handler_top__DOT__u_orders__DOT__pack_entry__7__ld;
        CData/*0:0*/ __Vfunc_feed_handler_top__DOT__u_orders__DOT__pack_entry__7__sd;
        CData/*0:0*/ __Vfunc_feed_handler_top__DOT__u_orders__DOT__pack_entry__8__ld;
        CData/*0:0*/ __Vfunc_feed_handler_top__DOT__u_orders__DOT__pack_entry__8__sd;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_orders__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_levels__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_levels__DOT__u_ask_bbo__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_levels__DOT__u_bid_bbo__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_levels__DOT__u_ask_upd__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_levels__DOT__u_bid_upd__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_decode__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_frame__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__feed_handler_top__DOT__u_hdr__DOT__clk__0;
        VL_IN16(cfg_locate,15,0);
        SData/*15:0*/ feed_handler_top__DOT__cfg_locate;
        SData/*15:0*/ feed_handler_top__DOT__hp_count;
        SData/*15:0*/ feed_handler_top__DOT__dc_locate;
    };
    struct {
        SData/*15:0*/ feed_handler_top__DOT__dc_tick;
        SData/*11:0*/ feed_handler_top__DOT__ot_m_tick;
        SData/*15:0*/ feed_handler_top__DOT__unused_tick_hi;
        SData/*11:0*/ feed_handler_top__DOT__pl_bid_tick;
        SData/*11:0*/ feed_handler_top__DOT__pl_ask_tick;
        SData/*11:0*/ feed_handler_top__DOT__u_orders__DOT__s_tick;
        SData/*11:0*/ feed_handler_top__DOT__u_orders__DOT__m_tick;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__init_idx;
        SData/*11:0*/ feed_handler_top__DOT__u_orders__DOT__op_tick;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__idx_a;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__idx_b;
        SData/*11:0*/ feed_handler_top__DOT__u_orders__DOT__pend_tick;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__a_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__b_addr;
        SData/*15:0*/ feed_handler_top__DOT__u_orders__DOT__st_valid;
        SData/*15:0*/ feed_handler_top__DOT__u_orders__DOT__st_ladder;
        SData/*15:0*/ feed_handler_top__DOT__u_orders__DOT__st_side;
        SData/*11:0*/ feed_handler_top__DOT__u_orders__DOT__e_tick;
        SData/*15:0*/ feed_handler_top__DOT__u_orders__DOT__st_busy;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__a_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__b_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__a_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__b_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__a_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__b_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__a_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__b_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__a_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__b_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__a_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__b_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__a_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__b_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__a_addr;
        SData/*13:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__b_addr;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__s_tick;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__m_bid_tick;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__m_ask_tick;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__s1_tick;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__wr_tick;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__best_bid_tick;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__best_ask_tick;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_bbo__DOT__waddr;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_bbo__DOT__raddr;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_bbo__DOT__waddr;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_bbo__DOT__raddr;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_upd__DOT__waddr;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_upd__DOT__raddr;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_upd__DOT__waddr;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_upd__DOT__raddr;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__index;
        SData/*11:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__index;
        SData/*15:0*/ feed_handler_top__DOT__u_decode__DOT__m_locate;
        SData/*15:0*/ feed_handler_top__DOT__u_decode__DOT__m_tick;
        SData/*15:0*/ feed_handler_top__DOT__u_decode__DOT__locate;
        SData/*15:0*/ feed_handler_top__DOT__u_decode__DOT__tick_c;
        SData/*15:0*/ feed_handler_top__DOT__u_frame__DOT__msg_idx;
        SData/*10:0*/ feed_handler_top__DOT__u_frame__DOT__ins_shift;
        SData/*15:0*/ feed_handler_top__DOT__u_frame__DOT__msg_len;
        SData/*10:0*/ feed_handler_top__DOT__u_frame__DOT__con_shift;
        SData/*15:0*/ feed_handler_top__DOT__u_hdr__DOT__m_count;
        SData/*15:0*/ feed_handler_top__DOT__u_hdr__DOT__ethertype_outer;
        SData/*15:0*/ feed_handler_top__DOT__u_hdr__DOT__ethertype_inner;
        SData/*15:0*/ feed_handler_top__DOT__u_hdr__DOT__ip_total_len;
    };
    struct {
        SData/*15:0*/ feed_handler_top__DOT__u_hdr__DOT__payload_len;
        SData/*15:0*/ feed_handler_top__DOT__u_hdr__DOT__mold_cnt;
        SData/*15:0*/ feed_handler_top__DOT__u_hdr__DOT__out_total;
        SData/*15:0*/ feed_handler_top__DOT__u_hdr__DOT__out_n;
        SData/*15:0*/ feed_handler_top__DOT__u_hdr__DOT__pay_len_q;
        SData/*11:0*/ __Vfunc_feed_handler_top__DOT__u_orders__DOT__pack_entry__7__tk;
        SData/*11:0*/ __Vfunc_feed_handler_top__DOT__u_orders__DOT__pack_entry__8__tk;
        VL_IN(cfg_band_base,31,0);
        VL_OUT(m_bid_price,31,0);
        VL_OUT(m_bid_qty,31,0);
        VL_OUT(m_ask_price,31,0);
        VL_OUT(m_ask_qty,31,0);
        VL_OUT(stat_packets,31,0);
        VL_OUT(stat_dropped,31,0);
        VL_OUT(stat_messages,31,0);
        VL_OUT(stat_frame_err,31,0);
        VL_OUT(stat_ops,31,0);
        VL_OUT(stat_other_symbol,31,0);
        VL_OUT(stat_out_of_band,31,0);
        VL_OUT(stat_subpenny,31,0);
        VL_OUT(stat_collisions,31,0);
        VL_OUT(stat_missing,31,0);
        VL_OUT(stat_overrun,31,0);
        VL_OUT(stat_stash_peak,31,0);
        VL_OUT(stat_underflow,31,0);
        IData/*31:0*/ feed_handler_top__DOT____VlemCond_3;
        IData/*31:0*/ feed_handler_top__DOT____VlemCall_2__tick_to_price;
        IData/*31:0*/ feed_handler_top__DOT____VlemCond_1;
        IData/*31:0*/ feed_handler_top__DOT____VlemCall_0__tick_to_price;
        IData/*31:0*/ feed_handler_top__DOT__cfg_band_base;
        IData/*31:0*/ feed_handler_top__DOT__m_bid_price;
        IData/*31:0*/ feed_handler_top__DOT__m_bid_qty;
        IData/*31:0*/ feed_handler_top__DOT__m_ask_price;
        IData/*31:0*/ feed_handler_top__DOT__m_ask_qty;
        IData/*31:0*/ feed_handler_top__DOT__stat_packets;
        IData/*31:0*/ feed_handler_top__DOT__stat_dropped;
        IData/*31:0*/ feed_handler_top__DOT__stat_messages;
        IData/*31:0*/ feed_handler_top__DOT__stat_frame_err;
        IData/*31:0*/ feed_handler_top__DOT__stat_ops;
        IData/*31:0*/ feed_handler_top__DOT__stat_other_symbol;
        IData/*31:0*/ feed_handler_top__DOT__stat_out_of_band;
        IData/*31:0*/ feed_handler_top__DOT__stat_subpenny;
        IData/*31:0*/ feed_handler_top__DOT__stat_collisions;
        IData/*31:0*/ feed_handler_top__DOT__stat_missing;
        IData/*31:0*/ feed_handler_top__DOT__stat_overrun;
        IData/*31:0*/ feed_handler_top__DOT__stat_stash_peak;
        IData/*31:0*/ feed_handler_top__DOT__stat_underflow;
        VlWide<13>/*399:0*/ feed_handler_top__DOT__mf_msg;
        IData/*31:0*/ feed_handler_top__DOT__dc_qty;
        IData/*31:0*/ feed_handler_top__DOT__dc_price;
        IData/*31:0*/ feed_handler_top__DOT__ot_m_qty;
        IData/*31:0*/ feed_handler_top__DOT__pl_bid_qty;
        IData/*31:0*/ feed_handler_top__DOT__pl_ask_qty;
        IData/*31:0*/ feed_handler_top__DOT__pl_updates;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT____VlemCond_1;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT____VlemCall_0__pack_entry;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__s_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__m_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__stat_collisions;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__stat_missing;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__stat_overrun;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__stat_stash_peak;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__op_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__pend_qty;
    };
    struct {
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__a_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__b_din;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__e_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__take_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__st_count;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__unnamedblk2__DOT__w;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__unnamedblk3__DOT__k;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__unnamedblk4__DOT__w;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__unnamedblk5__DOT__k;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__unnamedblk6__DOT__w;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__unnamedblk7__DOT__k;
        IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__unnamedblk8__DOT__k;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__a_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__a_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__b_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__b_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__a_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__a_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__b_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__b_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__a_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__a_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__b_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__b_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__a_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__a_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__b_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__b_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__a_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__a_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__b_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__b_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__a_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__a_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__b_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__b_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__a_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__a_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__b_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__b_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__a_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__a_dout;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__b_din;
        VlWide<4>/*96:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__b_dout;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__s_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__m_bid_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__m_ask_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__stat_updates;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__stat_underflow;
        VlWide<128>/*4095:0*/ feed_handler_top__DOT__u_levels__DOT__bid_map;
        VlWide<128>/*4095:0*/ feed_handler_top__DOT__u_levels__DOT__ask_map;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__s1_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__rd_bid;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__rd_ask;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__wr_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__base_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__new_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__bbo_bid_q;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__bbo_ask_q;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_bbo__DOT__wdata;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_bbo__DOT__rdata;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_bbo__DOT__wdata;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_bbo__DOT__rdata;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_upd__DOT__wdata;
    };
    struct {
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_upd__DOT__rdata;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_upd__DOT__wdata;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_upd__DOT__rdata;
        VlWide<128>/*4095:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__bitmap;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__unnamedblk5__DOT__g;
        VlWide<128>/*4095:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__bitmap;
        IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__unnamedblk5__DOT__g;
        VlWide<13>/*399:0*/ feed_handler_top__DOT__u_decode__DOT__s_msg;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__cfg_band_base;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__m_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__m_price;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__stat_ops;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__stat_out_of_band;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__stat_subpenny;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__add_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__add_price;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__red_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__rep_qty;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__rep_price;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__qty_c;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__price_c;
        IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__delta;
        VlWide<13>/*399:0*/ feed_handler_top__DOT__u_frame__DOT__m_msg;
        IData/*31:0*/ feed_handler_top__DOT__u_frame__DOT__stat_messages;
        IData/*31:0*/ feed_handler_top__DOT__u_frame__DOT__stat_frame_err;
        VlWide<16>/*511:0*/ feed_handler_top__DOT__u_frame__DOT__buf_q;
        VlWide<16>/*511:0*/ feed_handler_top__DOT__u_frame__DOT__ins_data;
        VlWide<16>/*511:0*/ feed_handler_top__DOT__u_frame__DOT__wide;
        VlWide<16>/*511:0*/ feed_handler_top__DOT__u_frame__DOT__buf_next;
        IData/*31:0*/ feed_handler_top__DOT__u_frame__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ feed_handler_top__DOT__u_hdr__DOT__stat_packets;
        IData/*31:0*/ feed_handler_top__DOT__u_hdr__DOT__stat_dropped;
        IData/*31:0*/ feed_handler_top__DOT__u_hdr__DOT__unnamedblk1__DOT__b;
        VlWide<4>/*96:0*/ __Vfunc_feed_handler_top__DOT__u_orders__DOT__pack_entry__7__Vfuncout;
        IData/*31:0*/ __Vfunc_feed_handler_top__DOT__u_orders__DOT__pack_entry__7__q;
        IData/*31:0*/ __Vfunc_feed_handler_top__DOT__u_orders__DOT__pack_entry__8__q;
        VL_IN64(s_tdata,63,0);
        VL_OUT64(m_bbo_seq,63,0);
        QData/*63:0*/ feed_handler_top__DOT__s_tdata;
        QData/*63:0*/ feed_handler_top__DOT__m_bbo_seq;
        QData/*63:0*/ feed_handler_top__DOT__hp_tdata;
        QData/*63:0*/ feed_handler_top__DOT__hp_seq;
        QData/*63:0*/ feed_handler_top__DOT__mf_seq;
        QData/*63:0*/ feed_handler_top__DOT__dc_ref;
        QData/*63:0*/ feed_handler_top__DOT__dc_new_ref;
        QData/*63:0*/ feed_handler_top__DOT__dc_seq;
        QData/*63:0*/ feed_handler_top__DOT__ot_m_seq;
        QData/*63:0*/ feed_handler_top__DOT__pl_bbo_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_orders__DOT__s_ref;
        QData/*63:0*/ feed_handler_top__DOT__u_orders__DOT__s_new_ref;
        QData/*63:0*/ feed_handler_top__DOT__u_orders__DOT__s_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_orders__DOT__m_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_orders__DOT__op_ref;
        QData/*63:0*/ feed_handler_top__DOT__u_orders__DOT__op_new_ref;
        QData/*63:0*/ feed_handler_top__DOT__u_orders__DOT__op_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_orders__DOT__pend_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_levels__DOT__s_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_levels__DOT__m_bbo_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_levels__DOT__s1_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_levels__DOT__wr_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__summary;
        QData/*63:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__grp_bits;
        QData/*63:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__summary;
        QData/*63:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__grp_bits;
    };
    struct {
        QData/*63:0*/ feed_handler_top__DOT__u_decode__DOT__s_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_decode__DOT__m_ref;
        QData/*63:0*/ feed_handler_top__DOT__u_decode__DOT__m_new_ref;
        QData/*63:0*/ feed_handler_top__DOT__u_decode__DOT__m_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_decode__DOT__add_ref;
        QData/*63:0*/ feed_handler_top__DOT__u_decode__DOT__red_ref;
        QData/*63:0*/ feed_handler_top__DOT__u_decode__DOT__rep_new_ref;
        QData/*63:0*/ feed_handler_top__DOT__u_decode__DOT__ref_c;
        QData/*63:0*/ feed_handler_top__DOT__u_decode__DOT__new_ref_c;
        QData/*63:0*/ feed_handler_top__DOT__u_decode__DOT__scaled;
        QData/*63:0*/ feed_handler_top__DOT__u_frame__DOT__s_tdata;
        QData/*63:0*/ feed_handler_top__DOT__u_frame__DOT__s_sequence;
        QData/*63:0*/ feed_handler_top__DOT__u_frame__DOT__m_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_hdr__DOT__s_tdata;
        QData/*63:0*/ feed_handler_top__DOT__u_hdr__DOT__m_tdata;
        QData/*63:0*/ feed_handler_top__DOT__u_hdr__DOT__m_sequence;
        QData/*63:0*/ feed_handler_top__DOT__u_hdr__DOT__prev_data;
        QData/*63:0*/ feed_handler_top__DOT__u_hdr__DOT__mold_seq;
        QData/*63:0*/ feed_handler_top__DOT__u_hdr__DOT__realigned;
        QData/*63:0*/ feed_handler_top__DOT__u_hdr__DOT__flushed;
        QData/*63:0*/ __Vfunc_feed_handler_top__DOT__u_orders__DOT__pack_entry__7__r;
        QData/*63:0*/ __Vfunc_feed_handler_top__DOT__u_orders__DOT__pack_entry__8__r;
        VlUnpacked<VlWide<4>/*96:0*/, 8> feed_handler_top__DOT__u_orders__DOT__rd_a;
        VlUnpacked<VlWide<4>/*96:0*/, 8> feed_handler_top__DOT__u_orders__DOT__rd_b;
        VlUnpacked<QData/*63:0*/, 16> feed_handler_top__DOT__u_orders__DOT__st_ref;
        VlUnpacked<SData/*11:0*/, 16> feed_handler_top__DOT__u_orders__DOT__st_tick;
        VlUnpacked<IData/*31:0*/, 16> feed_handler_top__DOT__u_orders__DOT__st_qty;
        VlUnpacked<VlWide<4>/*96:0*/, 16384> feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__mem;
        VlUnpacked<VlWide<4>/*96:0*/, 16384> feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__mem;
        VlUnpacked<VlWide<4>/*96:0*/, 16384> feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__mem;
        VlUnpacked<VlWide<4>/*96:0*/, 16384> feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__mem;
        VlUnpacked<VlWide<4>/*96:0*/, 16384> feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__mem;
        VlUnpacked<VlWide<4>/*96:0*/, 16384> feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__mem;
        VlUnpacked<VlWide<4>/*96:0*/, 16384> feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__mem;
        VlUnpacked<VlWide<4>/*96:0*/, 16384> feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__mem;
        VlUnpacked<IData/*31:0*/, 4096> feed_handler_top__DOT__u_levels__DOT__u_ask_bbo__DOT__mem;
        VlUnpacked<IData/*31:0*/, 4096> feed_handler_top__DOT__u_levels__DOT__u_bid_bbo__DOT__mem;
        VlUnpacked<IData/*31:0*/, 4096> feed_handler_top__DOT__u_levels__DOT__u_ask_upd__DOT__mem;
        VlUnpacked<IData/*31:0*/, 4096> feed_handler_top__DOT__u_levels__DOT__u_bid_upd__DOT__mem;
        VlUnpacked<CData/*7:0*/, 128> feed_handler_top__DOT__u_hdr__DOT__hb;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<CData/*7:0*/, 128>, false, CData/*7:0*/, 1> __VdlyCommitQueuefeed_handler_top__DOT__u_hdr__DOT__hb;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__HIGHEST = 0U;
    static constexpr CData/*0:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__HIGHEST = 1U;
    static constexpr CData/*7:0*/ feed_handler_top__DOT__u_hdr__DOT__HDR_BEATS = 0x10U;
    static constexpr CData/*7:0*/ feed_handler_top__DOT__u_hdr__DOT__PARAM_BEAT = 4U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__DW = 0x00000040U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__MAX_MSG = 0x00000032U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__SETS = 0x00004000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__WAYS = 8U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__STASH = 0x00000010U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__BAND_TICKS = 0x00001000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__TW = 0x0000000cU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__SETS = 0x00004000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__WAYS = 8U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__STASH = 0x00000010U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__TICK_W = 0x0000000cU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__IDX_W = 0x0000000eU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__WAY_W = 3U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__STS_W = 4U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__TAG_W = 0x00000032U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__E_TICK = 0x00000020U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__E_SIDE = 0x0000002cU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__E_TAG = 0x0000002dU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__E_LADDER = 0x0000005fU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__E_VALID = 0x00000060U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__ENTRY_W = 0x00000061U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__DW = 0x00000061U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__7__KET____DOT__u_way__DOT__AW = 0x0000000eU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__DW = 0x00000061U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__6__KET____DOT__u_way__DOT__AW = 0x0000000eU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__DW = 0x00000061U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__5__KET____DOT__u_way__DOT__AW = 0x0000000eU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__DW = 0x00000061U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__4__KET____DOT__u_way__DOT__AW = 0x0000000eU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__DW = 0x00000061U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__3__KET____DOT__u_way__DOT__AW = 0x0000000eU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__DW = 0x00000061U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__2__KET____DOT__u_way__DOT__AW = 0x0000000eU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__DW = 0x00000061U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__1__KET____DOT__u_way__DOT__AW = 0x0000000eU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__DW = 0x00000061U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_orders__DOT__g_way__BRA__0__KET____DOT__u_way__DOT__AW = 0x0000000eU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__BAND_TICKS = 0x00001000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__GW = 0x00000040U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__TW = 0x0000000cU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_bbo__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_bbo__DOT__DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_bbo__DOT__AW = 0x0000000cU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_bbo__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_bbo__DOT__DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_bbo__DOT__AW = 0x0000000cU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_upd__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_upd__DOT__DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_upd__DOT__AW = 0x0000000cU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_upd__DOT__DW = 0x00000020U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_upd__DOT__DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_upd__DOT__AW = 0x0000000cU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__W = 0x00001000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__GW = 0x00000040U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__NG = 0x00000040U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__GW_LG = 6U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_ask_pe__DOT__NG_LG = 6U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__W = 0x00001000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__GW = 0x00000040U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__NG = 0x00000040U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__GW_LG = 6U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_levels__DOT__u_bid_pe__DOT__NG_LG = 6U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__MAX_MSG = 0x00000032U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__BAND_TICKS = 0x00001000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__BAND_SPAN = 0x00064000U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_decode__DOT__RECIP_100 = 0x51eb851fU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_frame__DOT__DW = 0x00000040U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_frame__DOT__MAX_MSG = 0x00000032U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_frame__DOT__BUF_BYTES = 0x00000040U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_frame__DOT__BW = 8U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_frame__DOT__BUF_W = 0x00000200U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_frame__DOT__SHIFT_W = 0x0000000bU;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_hdr__DOT__DW = 0x00000040U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_hdr__DOT__HDR_BYTES = 0x00000080U;
    static constexpr IData/*31:0*/ feed_handler_top__DOT__u_hdr__DOT__BW = 8U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
